### ISSUE TITLE
Rotate the screen?

### ISSUE THREAD

**Issue by MarkoDamien** [goodtft/LCD-show#92]
Is there a possibility to rotate the screen? Like for 180 Degrees

**Comment by jantman** [comment]
Yes, edit ``/boot/config.txt``.

Using the installer here, it will have a line in it like  ``dtoverlay=tft35a``

If you want to rotate 180 from the default, change that to ``dtoverlay=tft35a:rotate=270``

(note the default seems to be 90...)

**Comment by MrEdinLaw** [comment]
I can confirm this works, Thanks

**Comment by MrEdinLaw** [comment]
> Yes, edit `/boot/config.txt`.
> 
> Using the installer here, it will have a line in it like `dtoverlay=tft35a`
> 
> If you want to rotate 180 from the default, change that to `dtoverlay=tft35a:rotate=270`
> 
> (note the default seems to be 90...)

This seems to rotate the screen but not the touch. The touch seems to stay the same

**Comment by andrew-rbd** [comment]
How about for the mhs35? I tried:
dtoverlay=mhs35:rotate=90
and it does not work.

**Comment by goodtft** [comment]
Is there any printed MHS-3.5inch printed on the back of the 3.5inch screen you purchased?
If there is no such silk screen, then you are using ordinary version module, instead of dtoverlay=mhs35 instruction, you use tft35a-overlay. DTB


2019-04-29 

goodtft 



发件人：Andrew Bryant <notifications@github.com>
发送时间：2019-04-27 04:31
主题：Re: [goodtft/LCD-show] Rotate the screen? (#92)
收件人："goodtft/LCD-show"<LCD-show@noreply.github.com>
抄送："goodtft"<goodtft@163.com>,"State change"<state_change@noreply.github.com>

How about for the mhs35? I tried:
dtoverlay=mhs35:rotate=90
and it does not work.

**Comment by goodtft** [comment]
Try：
dtoverlay=mhs35:rotate=0

2019-04-29 

goodtft 



发件人：Andrew Bryant <notifications@github.com>
发送时间：2019-04-27 04:31
主题：Re: [goodtft/LCD-show] Rotate the screen? (#92)
收件人："goodtft/LCD-show"<LCD-show@noreply.github.com>
抄送："goodtft"<goodtft@163.com>,"State change"<state_change@noreply.github.com>

How about for the mhs35? I tried:
dtoverlay=mhs35:rotate=90
and it does not work.

**Comment by andrew-rbd** [comment]
MHS-3.5inch Display is printed on the back of the display.

_____

Andrew Bryant  |  Founder & CEO
Right Brain Development
 
695 East McGlincy Lane Suite A
Campbell, CA 95008

office 1-408-840-2003 ext. 102
mobile 1-408-348-2173
 
https://rightbraindev.com
